config/routes.rb
Rails.application.routes.draw do

  	devise_for :users
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root :to => 'root#top'
	root 'books#index'#ログイン後マイページ
	get '/home/about' => 'home#about'
	resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]

	resources :users, only: [:show, :edit, :index, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 199}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: {maximum: 50}

#Userモデルとbooksを関連付け
  has_many :books, dependent: :destroy
  #refile使う時はattachment
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	#authenticate_user!はdeviseのメソッド.未ログインはrootパスへ
	before_action :authenticate_user!, except: [:top, :about]
	#devise利用する前にconfigure_permitted_parametersが実行
	before_action :configure_permitted_parameters, if: :devise_controller?


	protected#他コントローラからも
#サインアップ時ユーザnameのデータ操作許可
	def configure_permitted_parameters
#デフォでemail受け取ってるのを上書きしてしまうのでupにはemail追記
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    	devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  	end

	def after_sign_in_path_for(resource)
	    user_path(resource) # ログイン後に遷移するpathを設定
	end
	def after_sign_up_path_for(resource)
		user_path(resource)
	end


	private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	@book.user_id = current_user.id
  	if @book.save
      flash[:success] = 'Book was successfully created.'
      redirect_to book_path(@book.id)
    else
#renderでindex飛んでもここの変数を使うので@books持ってくる
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user#ユーザ詳細ページ
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find_by(id: @book.user)
#findはidのみなので
  end

  def edit
    @book = Book.find(params[:id])
#ログインユーザではないならURLからも編集不可
    if @book.user_id != current_user.id
      redirect_to book_path(@book.id)
    end
  end


  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:success] = 'Book was successfully updated.'
      redirect_to book_path(book.id)
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end


  private

  def book_params
  	params.require(:book).permit(:user_id, :title, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def about
	end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	def top
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#マイページ
  def show
  	@user = User.find(params[:id])
    #@booksにその@userに紐づいたbooksのみを渡す(pageはkaminariメソッド)
  	@books = @user.books.page(params[:page]).reverse_order
    @book = Book.new
  end

  def edit
  	@user = User.find(params[:id])
    #ログインユーザのみedit
    if @user.id != current_user.id
     redirect_to user_path(@user.id)
    end
  end

  def index
  	@users = User.all
    @user = current_user#ユーザ詳細
    @book = Book.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render "/users/edit"
    end
  end



  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>New Book</h2>
	<div class="row">
	<%= form_for(book) do |f| %>
		<h4>Title</h4><br>
			<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>
	<div class="row">
		<h4>Opinion</h4><br>
			<%= f.text_area :body, class: "col-xs-12 book_body" %><br>
	</div>
	<br>
	<div class ="row">
			<%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
	</div>
	<% end %>

<!-- いんすたふか -->
<%# <%= render 'books/list', book: @book %>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<%= form_for(@book) do |f| %>
				<p class="edit-headline">Title</p><br>
				<div class="row">
					<%= f.text_field :title, class: "col-xs-12 book_title" %>
				</div>
				<p class="edit-headline">Body</p>
				<div class="row">
					<%= f.text_area :body, class: "col-xs-12 book_body" %><br>
				</div>
				<div class="row">
					<%= f.submit 'Update Book', class: "btn btn-primary col-xs-12" %>
				</div>
			<% end %>

			<p>
			<%= link_to "show", book_path , class: "book_#{@book.id}" %> |
			<%= link_to "Back", '/books', class: "back" %>
			</p>
		</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
<%= form_for(@book) do |f| %>
	<% if @book.errors.any? %>
		<h3><%= @book.errors.count %>errors prohibited this obj from being saved:</h3>
		<ul>
		<% @book.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
		</ul>
	<% end %>
<% end %>

	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/list', user: @user %>
			<br>
			<br>
			<%= render 'books/list', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<table class="table">
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%#画像をリンクにしてる%>
							<%= link_to user_path(book.user.id) do %>
								<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class: "user_image" %>
							<% end %>
						</td>
						<td>
							<%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %>
						</td>
						<td>
							<span><%= book.body %></span><br>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/books/new.html.erb
<h2>New Book</h2>
<%= form_for(@book) do |f| %>
	<h4>Title</h4><br>
		<%= f.text_field :title, class: "book_title" %>
	<h4>Opinion</h4><br>
		<%= f.text_area :body, class: "book_body" %><br>
<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div class="container">
<%#サクセスメッセ%>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/list', user: @user %>
			<br>
			<%= render 'books/list', book: @book %>
		</div>

		<section class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table">
				<tr>
					<td>
						<%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", class: "user_image" %><br>
						<%= link_to @book.user.name, user_path(@book.user.id), class: "user_#{@book.user.id}" %>
					</td>
					<td>
						<%= @book.title %>
					</td>
					<td>
						<%= @book.body %>
					</td>
					<% if @book.user == current_user %>
						<td>
							<%= link_to "edit", edit_book_path , class: "btn-sm btn-success edit_book_#{@book.id}" %>
						</td>
						<td>
							<%= link_to "Destroy", book_path, method: :delete, "data-confirm" => "本当に消しますか？", class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
						</td>
					<% end %>
				</tr>
			</table>
		</section>
	</div>
</div>

app/views/home/about.html.erb
<div class="container">
	<h1>Welcome to<span class="glyphicon glyphicon-book"></span>Bookers!</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left text-white">
      <a class="navbar-brand" href="#">
        Bookers
      </a>

        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li>
                <%= link_to " Home", user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
                <%= link_to " Users", "/users", class: "glyphicon glyphicon-user users" %>
              </li>
              <li>
                <%= link_to " Books", "/books", class: "glyphicon glyphicon-book books" %>
              </li>
              <li>
                <%= link_to " logout", destroy_user_session_path, method: :delete, class: "glyphicon glyphicon-log-out logout" %>
              </li>
            <% else %>
              <li>
                <%= link_to " Home", "/", class: "glyphicon glyphicon-home home" %>
              </li>
              <li>
                <%= link_to " About", "/home/about", class: "glyphicon glyphicon-link about" %>
              </li>
              <li>
                <%= link_to " sign up", new_user_registration_path, class: "glyphicon glyphicon-edit sign_up" %>
              </li>
              <li>
                <%= link_to " login", new_user_session_path, class: "glyphicon glyphicon-log-in sign_in" %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <P>CopyRight Infratop.inc</P>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/root/top.html.erb
<div class="container">
	<div class="row">
		<div class="top-message col-md-offset-3 col-md-6">
			<h1>welcome to
				<span class="glyphicon glyphicon-book"></span>Bookers !!
			</h1>
			<p>In<span class="glyphicon glyphicon-book"></span>
				<strong>Bookers,</strong>
			</p>

			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>
			<%= link_to 'Log in', "/users/sign_in", class: "btn btn-info col-xs-10 col-xs-offset-1 sign_in" %><br>
			<%= link_to 'Sign Up', "/users/sign_up", class: "btn btn-success col-xs-10 col-xs-offset-1 sign_up" %>
		</div>
	</div>
</div>

app/views/users/_list.html.erb
<h2>User info</h2>
	<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", class: "user_image" %>
	<table class="table">
		<tr>
			<td>
				<strong>name</strong>
			</td>
			<td>
				<%= user.name %>
			</td>
		</tr>
		<tr>
			<td>
				<strong>introduction</strong>
			</td>
			<td>
				<%= current_user.introduction %>
			</td>
		</tr>
	</table>

    <% if user.id == current_user.id %>
    <p><%= link_to "", edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %></p>
 	<% end %>

<%# <%= render 'users/list', user: @user %>

app/views/users/edit.html.erb
<div class="container">
	<h2 class="form-header-title">User info</h2>
	<%= form_for(@user) do |f| %>
		<% if @user.errors.any? %>
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
			</ul>
		<% end %>
	<% end %>

	<div class="form-body">
		<%= form_for(@user) do |f| %>
			<p><strong>Name</strong>
		        <%= f.text_field :name, autofocus: true, class: "name" %>
		    </p>
			<p><strong>Image</strong></p><br>
			<label class="control-label sr-only" for="inputEmail"></label>
		    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user_image" %>

			<p><strong>Introduction</strong>
				<%= f.text_area :introduction, autofocus: true, class: "introduction" %>
			</p>

		    <%= f.submit "Update User", class: "" %>
		<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/list', user: @user %>
			<%= render 'books/list', book: @book %>
		</div>

		<div class="col-xs-9">
			<h2 class="users-title">Users</h2>
			<table class="table">
				<tr>
					<th>image</th>
					<th>name</th>
					<th><%#show欄%></th>
				</tr>
				<% @users.each do |user| %>
					<tr>
						<td>
							<%= attachment_image_tag user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "user_image", fallback: "no_image.jpg" %>
						</td>
						<td>
							<%= user.name %>
						</td>
						<td>
							<%= link_to 'show', user_path(user.id), class: "user_#{user.id}" %>
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%#boostrapのサクセウメッセ%>
<div class="container">
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>


	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/list', user: @user %>
			<br>
			<br>
			<%= render 'books/list', book: @book %>
		</div>

		<section class="col-xs-9">
			<h1>Books</h1>
			<table class="table">
				<tr>
					<th><%#プロフ画%></th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, format: 'jpeg', fallback: "no_image.jpg", class: "user_image" %>
						</td>
						<td>
							<%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %>
						</td>

						<td>
							<%= book.body %>
						</td>
					</tr>
				<% end %>
			</table>
		</section>
	</div>
</div>